#define TOKEN_ERROR                           1
#define TOKEN_PAR                             2
#define TOKEN_IN                              3
#define TOKEN_END                             4
#define TOKEN_USING                           5
#define TOKEN_DES                             6
#define TOKEN_LPAR                            7
#define TOKEN_NUMBER                          8
#define TOKEN_COMMA                           9
#define TOKEN_RPAR                           10
#define TOKEN_STRING                         11
#define TOKEN_ACTION                         12
#define TOKEN_HASH                           13
#define TOKEN_ARROW                          14
#define TOKEN_STAR                           15
#define TOKEN_UNDERSCORE                     16
#define TOKEN_BARS                           17
#define TOKEN_USER                           18
